# CD Workflow: Publish and Sync to Main
name: CD - Publish and Sync to Main

on:
  pull_request:
    types: [ closed ]
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Determine Package Version
        id: pkgversion
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "Stable release detected."
          VERSION="${{ steps.gitversion.outputs.NuGetVersion }}"
          else
          echo "Beta release detected."
          # Create a beta version by appending a beta suffix and the commit count
          VERSION="${{ steps.gitversion.outputs.MajorMinorPatch }}-beta.${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
          fi
          echo "Using version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Pack Project
        run: dotnet pack --configuration Release --no-build --output ./artifacts /p:PackageVersion=${{ steps.pkgversion.outputs.version }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

  sync_to_main:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request from release to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: sync/release-to-main
          base: main
          title: '${{ github.event.pull_request.title }}'
          body: '${{ github.event.pull_request.body }}'
          labels: automated-pr
          delete-branch: false
