# CD Workflow: Publish and Sync to Main
name: CD - Publish and Sync to Main

on:
  pull_request:
    types: [closed]
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  publish_and_sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11.0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack Project
        run: |
          dotnet pack --configuration Release --no-build \
            --output ./artifacts \
            /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GSALVI_TOOLKIT_GITHUB_TOKEN }}
          source-branch: release
          target-branch: main
          title: '${{ github.event.pull_request.title }}'
          body: '${{ github.event.pull_request.body }}'
          labels: automated-pr

      - name: Auto Merge Pull Request
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GSALVI_TOOLKIT_GITHUB_TOKEN }}
          MERGE_LABELS: automated-pr
          MERGE_METHOD: merge
